### ISSUE TITLE
Odd Negative Scaling

### ISSUE THREAD

**Issue by msklywenn** [Unity-Technologies/BatchBreakingCause#1]
Not really sure if this is the right place to ask but : Why is negative scaled objects an issue for batching ? Shouldn't it end up in the transform matrix just as anything else ? Especially with instancing.

**Comment by AlphaMistral** [comment]
Exactly the same question I wanna ask! In general batching finally resides in one single mesh, one single material and multiple transform matrices. Hence it looks weird that a flipped scale breaks batching.

**Comment by chaifix** [comment]
That's because odd negative scaling introduce a glFrontFace(GL_CCW) call，which change culling mode from GL_CW to GL_CCW. Mirroring a model could change chirality, from left hand to right hand. In order to keep correct culling, a inverse culling mode is required. But still, I dont know the reason why Unity doesn't modify indices order in IBO to handle this situation（by exchange two indices order in triangle）.

**Comment by chaifix** [comment]
> That's because odd negative scaling introduce a glFrontFace(GL_CCW) call，which change culling mode from GL_CW to GL_CCW. Mirroring a model could change chirality, from left hand to right hand. In order to keep correct culling, a inverse culling mode is required. But still, I dont know the reason why Unity doesn't modify indices order in IBO to handle this situation.

glFrontFace(GL_CCW) is a SetPass call. Remenber this, only batches under the same SetPass call cound be batched.

**Comment by chaifix** [comment]
> Exactly the same question I wanna ask! In general batching finally resides in one single mesh, one single material and multiple transform matrices. Hence it looks weird that a flipped scale breaks batching.

Batching doesn't create multiple matrices. No matter static batching or dynamic batching, Unity only create ONE vbo and ONE ibo. The difference is that static batching drawing meshes as "submesh" with indivitual glDrawElements call(aka drawcall), yet dynamic batching drawing meshes as one big mesh with one drawcall. That's for frustum culling purpose.

**Comment by chaifix** [comment]
> Exactly the same question I wanna ask! In general batching finally resides in one single mesh, one single material and multiple transform matrices. Hence it looks weird that a flipped scale breaks batching.

Batching doesn't create multiple matrices. No matter static batching or dynamic batching, Unity only create ONE vbo and ONE ibo. The difference is that static batching draw meshes as "submesh" with several indivitual glDrawElements call(aka drawcall), yet dynamic batching draw meshes as one big mesh with one drawcall. That's for frustum culling purpose.

**Comment by chaifix** [comment]
> That's because odd negative scaling introduce a glFrontFace(GL_CCW) call，which change culling mode from GL_CW to GL_CCW. Mirroring a model could change chirality, from left hand to right hand. In order to keep correct culling, a inverse culling mode is required. But still, I dont know the reason why Unity doesn't modify indices order in IBO to handle this situation.

glFrontFace(GL_CCW) is a SetPass call. Remenber this, only batches under the same SetPass cound be batched.
